Repository 9oormthonUNIV-ITC/itc-frontend, pull requests merged in 2025-05, with the labels that each got.

#138 ♻️ refactor: Update login-btn size
  src/pages/login-page.html
  src/style.css
Labels: ♻️Refactor

#139 💄 style: Update main-page section03
  public/images/ayu.svg
  public/images/hyu.svg
  public/images/inu.svg
  public/images/itc.svg
  public/images/jnu.svg
  public/images/section04-1.png
  public/images/section04-2.png
  public/images/section04-3.png
  public/images/section04-4.png
  public/images/section04-5.png
  public/images/tuk.svg
  public/images/univ-ayu.png
  public/images/univ-hyu.png
  public/images/univ-inu.png
  public/images/univ-itc.png
  public/images/univ-jnu.png
  public/images/univ-tuk.png
  src/pages/main-page.html
  src/style.css
Labels: 💄style

#141 ♻️ refactor: Update responsive UI design
  src/pages/main-page.html
Labels: ♻️Refactor

#142 Refactor/project page
  public/images/9oormthon_logo.png
  public/images/erica.svg
  public/images/jnu.svg
  public/images/tuk.svg
  public/images/ynu.svg
  src/js/project-page.js
  src/pages/project-page.html
Labels: ⚒️BugFix, 🔴 Priority : Very High, ♻️Refactor

#144 ♻️ refactor: Change Font-size
  src/pages/main-page.html
Labels: ♻️Refactor

#145 Refactor/project page(2)
  public/images/jnu.svg
  public/images/tuk.svg
  src/pages/project-page.html
Labels: 🔵 Priority : Low, ♻️Refactor, 💄style

#148 Refactor/main page/all
  src/pages/main-page.html
Labels: ♻️Refactor

#149 🖥 accessibility: Update heading structure and improve contrast ratio
  src/pages/main-page.html
  src/style.css
Labels: 🚀 Accessibility

#151 💄 style: Update head favicon
  src/pages/login-page.html
Labels: 💄style

#152 Refactor/project page
  src/js/project-page.js
Labels: ♻️Refactor

#153 Qa/project page
  src/pages/project-page.html
Labels: ♻️Refactor

#154 Qa/footer
  src/components/common-footer.html
  src/pages/project-page.html
Labels: ⚒️BugFix

#155 Qa/project page
  src/js/project-page.js
  src/pages/project-page.html
Labels: ♻️Refactor

#157 :recycle: refactor: Add top image
  src/pages/feed-page.html
Labels: 🏃 Feature

#159 Refactor/mypage
  src/pages/mypage-page.html
Labels: 🏃 Feature

#162 A11y/main page/validate
  src/js/main-card-img.js
  src/js/main-card-item.js
  src/pages/main-page.html
Labels: 🚀 Accessibility

#163 Feature/login page/login btn
  src/js/login-page.js
  src/pages/login-page.html
Labels: 🏃 Feature, 🚀 Accessibility

#164 🖥️ a11y: Change <svg> to <img>
  public/images/logo-purple.svg
  public/images/logo-purple2.svg
  public/images/logo-purple3.svg
  src/pages/main-page.html
Labels: 🚀 Accessibility

#166 🐛 fix: ensure edit modal uses flex display when shown
  src/js/project-page.js
Labels: ♻️Refactor

#167 Feature/login auth
  src/js/auth.js
  src/js/login-page.js
Labels: 🏃 Feature, 🔴 Priority : Very High

#171 :sparkles: feat: Prevent link to mypage
  src/js/common-header.js
Labels: 🏃 Feature

#173 Bugfix/feed page
  src/pages/feed-page.html
Labels: ⚒️BugFix

#174 Refactor/work page
  index.html
  src/js/common-header.js
  src/pages/feed-page.html
  src/pages/main-page.html
  src/pages/mypage-page.html
  src/pages/project-page.html
  vite.config.js
Labels: ⚒️BugFix, 🔴 Priority : Very High

#178 🖥️ a11y: Update login btn accessbility and Adjust main height
  src/js/login-page.js
  src/pages/login-page.html
Labels: 🚀 Accessibility
