Repository 9oormthonUNIV-ITC/itc-frontend, pull requests merged in 2025-04, with the labels that each got.

#13 💄style: Create common-input component
  src/components/common-input.html
Labels: 🏃 Feature

#14 💄style: Create project-card-item component
  src/components/project-card-item.html
Labels: 🏃 Feature

#18 Feature/project popover
  src/components/common-input.html
  src/components/project-popover.html
Labels: 🏃 Feature

#30 :sparkles: feat: Implement feed-card-item UI component
  index.html
  package-lock.json
  package.json
  src/components/feed-card-item.html
  src/js/feed-card-item.js
Labels: 🏃 Feature

#36 Feature/project page
  src/js/project-page.js
  src/pages/project-page.html
Labels: 🏃 Feature, 🟠 Priority : High

#39 :whale: chore: add project-page in index
  index.html
Labels: 🏃 Feature

#40 Feature/main page
  public/images/flower-group.png
  public/images/flower-pink.png
  public/images/flower-pink2.png
  public/images/univ-ayu.png
  public/images/univ-hyu.png
  public/images/univ-inu.png
  public/images/univ-itc.png
  public/images/univ-jnu.png
  public/images/univ-tuk.png
  src/components/common-btn.html
  src/pages/main-page.html
Labels: 🏃 Feature

#45 Feature/project page
  src/pages/project-page.html
Labels: ♻️Refactor

#47 ✨ feat: Improve UI responsiveness main page layout
  public/images/main-cloud.svg
  public/images/main-flower1.svg
  public/images/main-flower2.svg
  public/images/main-flower3.svg
  src/components/common-btn.html
  src/pages/main-page.html
Labels: 🏃 Feature

#50 Feature/project modal submit
  .gitignore
  src/js/project-page.js
  src/pages/project-page.html
Labels: 🏃 Feature, 🔴 Priority : Very High

#60 ♻️ refactor: Improve UI responsive and Add animation
  public/images/logo-pink.svg
  public/images/logo-pink2.svg
  public/images/logo-pink3.svg
  src/pages/main-page.html
  src/style.css
Labels: ♻️Refactor

#62 ✨ feat: Add mainpage wheel-event
  src/js/main-page.js
Labels: 🏃 Feature

#67 ✨ feat: Add login-page
  public/images/google-icon.png
  public/images/login-9oorm.png
  src/pages/login-page.html
Labels: 🏃 Feature

#69 Refactor/main page
  src/js/main-page.js
  src/pages/main-page.html
  src/style.css
Labels: ♻️Refactor

#70 Feature/project edit delete
  src/js/project-page.js
  src/pages/project-page.html
Labels: 🏃 Feature, ♻️Refactor

#76 :bug: bugfix: Restore vite.svg, javascript.svg
  javascript.svg
  public/vite.svg
  src/javascript.svg
Labels: ⚒️BugFix

#79 Feature/main page/tab slider
  src/js/main-card-img.js
  src/pages/main-page.html
  src/style.css
Labels: 🏃 Feature

#80 Feature/feed page preivew
  package-lock.json
  package.json
  src/js/feed-card-item.js
  src/js/feed-page.js
  src/pages/feed-page.html
Labels: 🏃 Feature

#82 :whale: chore: Connect nav link to each page
  index.html
  src/pages/feed-page.html
  src/pages/login-page.html
  src/pages/mypage-page.html
  src/pages/project-page.html
Labels: 🏃 Feature

#84 :lipstick: style: Center profile info in mypage
  src/pages/mypage-page.html
Labels: 🏃 Feature

#87 Refactor/project modal markup
  src/js/project-page.js
  src/pages/project-page.html
Labels: 🏃 Feature, ♻️Refactor

#88 Refactor/project modal markup(2)
  src/js/project-page.js
  src/pages/project-page.html
Labels: ♻️Refactor

#90 💄style/main page/section5
  src/js/main-card-img.js
  src/js/main-card-item.js
  src/pages/main-page.html
  src/style.css
Labels: 🏃 Feature, 💄style

#92 💄 style: Change flower img
  public/images/flower-group2.png
  src/pages/main-page.html
Labels: 💄style

#97 💄 style: Change Font-size
  src/pages/login-page.html
Labels: 💄style

#98 Style/main page/btn
  src/pages/main-page.html
Labels: 💄style

#99 💄 style: Adjust btn margin,padding
  src/pages/main-page.html
Labels: 💄style

#100 Refactor/project page
  public/images/character-1.svg
  public/images/character-2.svg
  public/images/character-3.svg
  public/images/character-4.svg
  public/images/character-5.svg
  public/images/character-6.svg
  public/images/character-7.svg
  public/images/character.svg
  src/js/project-page.js
  src/pages/project-page.html
Labels: 🏃 Feature, 🟠 Priority : High, ♻️Refactor

#102 Refactor/footer
  public/images/github.svg
  public/images/instagram.svg
  src/components/common-footer.html
  src/pages/project-page.html
Labels: 🟡 Priority : Midium, ♻️Refactor

#103 ♻️ refactor: Refactor Project Page
  src/pages/project-page.html
Labels: ♻️Refactor

#111 Feature/main page progress
  src/js/main-page.js
  src/pages/main-page.html
Labels: 🏃 Feature

#114 💄 style: Adjust main-page header
  src/pages/main-page.html
Labels: 💄style

#117 💄 style: Adjust main-page header duration
  src/pages/main-page.html
Labels: 💄style

#118 💄 style: Adjust main-page header padding-top
  src/pages/main-page.html
Labels: 💄style

#121 💄 style: Add main-section2 img
  public/images/mainsection02-1.webp
  public/images/mainsection02-2.webp
  src/pages/main-page.html
Labels: 💄style

#123 Style/main page footer
  src/pages/main-page.html
  src/style.css
Labels: 💄style

#127 Style/login page/refactor
  public/fonts/roboto/Roboto-Regular.ttf
  public/fonts/roboto/roboto.css
  src/pages/login-page.html
  src/style.css
Labels: 💄style

#128 :sparkles: feat: Add link preview feature with API integration
  .gitignore
  src/js/feed-page.js
Labels: 🏃 Feature
